config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  resources :users, only: [:show]
  resources :boats, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:new, :create, :update]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_many :boats
  has_many :bookings
  has_many :booked_boats, through: :boats, source: :bookings
  has_attachment :photo
  validates :first_name, :last_name, presence: true

  def self.find_for_facebook_oauth(auth)

    user_params = auth.to_h.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def bookings_by_time(bookings)
    past_bookings = bookings.select { |b| b.end_at < Date.today }
    future_bookings = bookings.select { |b| b.start_at > Date.today }
    present_bookings = bookings.select do |b|
      b.start_at <= Date.today && b.end_at >= Date.today || b.start_at >= Date.today && b.start_at <= Date.today
    end
    {
      past: past_bookings,
      future: future_bookings,
      present: present_bookings
    }
  end

  def user_photo(user)
    if user.photo?
      photo = user.photo
    elsif user.facebook_picture_url.nil? == false
      photo = user.facebook_picture_url
    elsif user.picture_url.nil? == false
      photo = user.picture_url
    else
      photo = "blank-profile-picture.svg"
    end
    photo
  end
end

app/views/users/_bookings.html.erb
<% bookings.each do |b| %>
  <p class=""><strong><%= b.boat.name %></strong></p>
  <p><%= b.start_at %> to <%= b.end_at %></p>
  <br>
<% end %>

app/views/users/_user_boat_cards.html.erb
<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),url(
<% if boat.photos? %>
  <%= cl_image_path boat.photos.first.path %>
<% elsif boat.image1.nil? == false %>
  <%= boat.image1 %>
<% else %>
  <%= "" %>
<% end %>
);">
  <div class="card-category"><%= boat.city %></div>
  <div class="card-description">
    <h2><%= boat.name %></h2>
    <p><%= boat.boat_type %></p>
  </div>

  <% link_to boat, class: "card-link" %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="user">
      <div class="col-sm-12">
        <div class="col-sm-4">
          <%= image_tag(user_photo(@user),id: "image-medium", class: "img-circle center-block") %>
          <h1 class="text-center"> <%= @user.first_name  %> <%= @user.last_name%> </h1>

          <% if  @user.phone_number %>
            <p> <%= image_tag "phone.png" %>  <%= @user.phone_number %></p>
          <% end %>

          <% if @user.email %>
            <p> <%= image_tag "email.png" %>  <%= @user.email %></p>
          <% end %>

          <% if @user.boat_license %>
            <p><%= image_tag "license_boat.png" %>  Licensed </p>
          <% else %>
            <p id="license-color"><%= image_tag "license_boat.png" %>  Not Licensed</p>
          <% end %>
        </div>

        <div class="col-sm-6 col-sm-offset-2">
          <% if @user == current_user %>
            <h2>Bookings :</h2>
            <% bookings = bookings_by_time(@user.bookings) %>
            <h3>Past</h3>
            <%= render 'users/bookings', bookings: bookings[:past] %>
            <h3>Future</h3>
            <%= render 'users/bookings', bookings: bookings[:future] %>
            <h3>Present</h3>
            <%= render 'users/bookings', bookings: bookings[:present] %>
          <% end %>
        </div>
      </div>
      <div class="row col-sm-12 padding-bottom-page">
        <hr>
        <h3 class="text-center"><%= @user.first_name %> boats</h3>
        <hr>
        <% @user.boats.each do |boat| %>
          <div class="col-xs-12 col-sm-4" style="margin-top: 10px">
            <%= link_to boat_path(boat) do %>
              <%= render 'user_boat_cards', boat: boat %>
            <% end %>
          </div>
        <% end %>
      </div>
  </div>
</div>