config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  resources :users, only: [:show]
  resources :boats, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:new, :create, :update]
  end

end

app/views/shared/_avatar.html.erb
<!-- Avatar -->

<img src="user.jpg" alt="user" class="avatar">
<img src="user.jpg" alt="user" class="avatar-large">
<img src="user.jpg" alt="user" class="avatar-bordered">
<img src='user.jpg' alt="user" class="avatar-square"/>

app/views/shared/_badge_icon.html.erb
<!-- Icon -->
<div class="badge-container">
  <i class="fa fa-envelope-o"></i>
  <div class="badge badge-blue">3</div>
</div>

app/views/shared/_badge_user.html.erb
<!-- User -->
<div class="badge-container">
  <img src="user.jpg" alt="user" class="avatar">
  <div class="badge badge-red">M</div>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('background.jpg');">
  <div class="banner-content">
    <h1>Some Stuff</h1>
    <p>Very cool stuff, useful and smart</p>
    <a class="btn btn-primary btn-lg">GET IT</a>
  </div>
</div>

app/views/shared/_button.html.erb
<!-- Button -->

<a href="#" class="btn-medium">Write a story</a>
<a href="#" class="btn-treehouse">Start now</a>

app/views/shared/_card.html.erb
<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('background.jpg');">
  <div class="card-category">Popular</div>
  <div class="card-description">
    <h2>Some stuff</h2>
    <p>Very cool stuff, useful and smart</p>
  </div>
  <img class="card-user avatar" src="user.jpg">
  <a class="card-link" href="#" ></a>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_list_item.html.erb
<div class="product">
  <div class='product-upvote'>
    <div class="product-arrow"></div>
    <div class='product-count'>95</div>
  </div>
  <div class='product-body'>
    <h3>Kudoz</h3>
    <p>Les meilleures offres d'emploi cadre sur mobile</p>
  </div>
  <ul class="list-inline product-controls hidden-sm hidden-xs">
    <li><a href=""><i class="fa fa-heart"></i></a></li>
    <li><a href=""><i class="fa fa-share"></i></a></li>
    <li><a href=""><i class="fa fa-star"></i></a></li>
  </ul>
</div>

app/views/shared/_list_item_hidden_controls.html.erb
<div class="product">
  <div class='product-upvote'>
    <div class="product-arrow"></div>
    <div class='product-count'>95</div>
  </div>
  <img src="kudoz.jpg" alt="kudoz" class="product-image hidden-xs">
  <div class='product-body'>
    <h3>Kudoz</h3>
    <p>Les meilleures offres d'emploi cadre sur mobile</p>
  </div>
  <ul class="list-inline product-controls product-controls-hidden hidden-sm hidden-xs">
    <li><a href=""><i class="fa fa-heart"></i></a></li>
    <li><a href=""><i class="fa fa-share"></i></a></li>
    <li><a href=""><i class="fa fa-star"></i></a></li>
  </ul>
</div>

app/views/shared/_list_item_image.html.erb
<div class="product">
  <div class='product-upvote'>
    <div class="product-arrow"></div>
    <div class='product-count'>95</div>
  </div>
  <img src="kudoz.jpg" alt="kudoz" class="product-image hidden-xs">
  <div class='product-body'>
    <h3>Kudoz</h3>
    <p>Les meilleures offres d'emploi cadre sur mobile</p>
  </div>
  <ul class="list-inline product-controls hidden-sm hidden-xs">
    <li><a href=""><i class="fa fa-heart"></i></a></li>
    <li><a href=""><i class="fa fa-share"></i></a></li>
    <li><a href=""><i class="fa fa-star"></i></a></li>
  </ul>
</div>

app/views/shared/_media_layout.html.erb
<div class="media">
  <div class="media-body">
    <div class="media-section">
      <h2>Pictures</h2>
      ...
    </div>
    <div class="media-section">
      <h2>Description</h2>
      ...
    </div>
  </div>
  <div class="media-aside">
    <div class="media-section">
      <h2>Share</h2>
      ...
    </div>
    <div class="media-section">
      <h2>382 upvotes</h2>
      ...
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="navbar-wagon">
    <div class="navbar-wagon-left">
      <!-- Logo -->
      <div>
        <%= link_to root_path, class: "navbar-wagon-brand" do %>
        <%= image_tag "logo_boat.png" %>
        <% end %>
      </div>
      <!-- Title -->
      <div class="navbar-wagon-title">
        <%= link_to root_path, id: "title" do %>
        <h4>SailAway</h4>
        <% end %>
      </div>
    </div>



    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">

      <!-- Search form -->
      <form class="navbar-wagon-search" action="/boats">
        <input type="text" name="destination" class="navbar-wagon-search-input" placeholder="Cherchez une ville">
        <button type="submit" class="navbar-wagon-search-btn">
          <i class="fa fa-search"></i>
        </button>
      </form>

      <!-- Different navigation if login or not -->
      <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
      <div class="badge-container">
        <i class="fa fa-envelope-o"></i>
        <div class="badge badge-blue">3</div>
      </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
            </li>
            <li>
              <%= link_to current_user do %>
              <i class="fa fa-user"></i> <%= t("Profile") %>
              <% end %>
              <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

      <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_in", default: "Register"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <% end %>

      <!-- Button (call-to-action) -->
      <%= link_to t(".top_call_to_action", default: "Ajoutez un bateau"), new_boat_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
    </div>


    <!-- Dropdown list appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Some mobile link</a></li>
          <li><a href="#">Other one</a></li>
          <li><a href="#">Other one</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_share_links.html.erb
<div class="share-links">
  <a href="#" class="share-link bg-facebook">
    <i class="fa fa-facebook"></i>
  </a>
  <a href="#" class="share-link bg-twitter">
    <i class="fa fa-twitter"></i>
  </a>
  <a href="#" class="share-link bg-email">
    <i class="fa fa-envelope-o"></i>
  </a>
  <a href="#" class="share-link bg-text">
    <i class="fa fa-mobile"></i>
  </a>
</div>

app/views/shared/_tabs.html.erb
<div class="tabs">
  <a class="tab active" href="#">
    <h3>350</h3>
    <p>Followers</p>
  </a>
  <a class="tab" href="#">
    <h3>456</h3>
    <p>Following</p>
  </a>
  <a class="tab" href="#">
    <h3>189</h3>
    <p>Upvoted</p>
  </a>
  <a class="tab" href="#">
    <h3>13</h3>
    <p>Submitted</p>
  </a>
</div>